In [2]:
from nba_api.stats.static import teams
import pandas as pd

In [7]:
celtics = [team for team in teams.get_teams() if team['abbreviation'] == 'BOS'][0]

In [8]:
celtics

{'id': 1610612738,
 'full_name': 'Boston Celtics',
 'abbreviation': 'BOS',
 'nickname': 'Celtics',
 'city': 'Boston',
 'state': 'Massachusetts',
 'year_founded': 1946}

In [9]:
celtics_id = celtics["id"]

In [10]:
from nba_api.stats.endpoints import leaguegamefinder

In [11]:
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=celtics_id)

In [12]:
games = gamefinder.get_data_frames()[0]

In [13]:
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22023,1610612738,BOS,Boston Celtics,0022300188,2023-11-13,BOS vs. NYK,None,109,40,...,0.750,3,13,16,11,0,1,4,6,0.8
1,22023,1610612738,BOS,Boston Celtics,0022300174,2023-11-11,BOS vs. TOR,W,242,117,...,0.615,5,41,46,30,1,4,12,14,23.0
2,22023,1610612738,BOS,Boston Celtics,0022300010,2023-11-10,BOS vs. BKN,W,241,121,...,0.714,17,35,52,29,5,3,7,13,14.0
3,22023,1610612738,BOS,Boston Celtics,0022300159,2023-11-08,BOS @ PHI,L,241,103,...,0.842,9,34,43,28,8,6,12,13,-3.0
4,22023,1610612738,BOS,Boston Celtics,0022300154,2023-11-06,BOS @ MIN,L,265,109,...,0.765,11,34,45,20,13,2,16,26,-5.0

In [14]:
games.groupby(games.SEASON_ID.str[-4:])[['GAME_ID']].count().loc['2015':]

           GAME_ID
SEASON_ID
2015           103
2016           115
2017           113
2018           101
2019           102
2020            80
2021           115
2022           111
2023            20

In [15]:
games_1718 = games[games.SEASON_ID.str[-4:] == '2017']

In [16]:
games_1718.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
529,42017,1610612738,BOS,Boston Celtics,0041700307,2018-05-27,BOS vs. CLE,L,240,79,...,0.737,11,31,42,18,6,0,5,20,-8.0
530,42017,1610612738,BOS,Boston Celtics,0041700306,2018-05-25,BOS @ CLE,L,241,99,...,0.550,5,26,31,25,5,2,13,18,-10.0
531,42017,1610612738,BOS,Boston Celtics,0041700305,2018-05-23,BOS vs. CLE,W,240,96,...,0.913,7,38,45,18,10,6,8,19,13.0
532,42017,1610612738,BOS,Boston Celtics,0041700304,2018-05-21,BOS @ CLE,L,239,102,...,0.767,9,28,37,21,9,3,9,26,-9.0
533,42017,1610612738,BOS,Boston Celtics,0041700303,2018-05-19,BOS @ CLE,L,240,86,...,0.786,6,28,34,16,4,4,15,25,-30.0

In [17]:
raps_games_1718 = games_1718[games_1718.MATCHUP.str.contains('TOR')]
raps_games_1718.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
552,22017,1610612738,BOS,Boston Celtics,0021701171,2018-04-04,BOS @ TOR,L,237,78,...,0.893,8,35,43,10,7,3,16,16,-18.0
554,22017,1610612738,BOS,Boston Celtics,0021701140,2018-03-31,BOS vs. TOR,W,240,110,...,0.852,8,33,41,19,6,3,5,23,11.0
575,22017,1610612738,BOS,Boston Celtics,0021700798,2018-02-06,BOS @ TOR,L,240,91,...,0.750,9,29,38,21,3,3,17,19,-20.0
616,22017,1610612738,BOS,Boston Celtics,0021700188,2017-11-12,BOS vs. TOR,W,239,95,...,0.789,15,31,46,24,9,2,14,18,1.0

In [18]:
last_raps_game = raps_games_1718.sort_values('GAME_DATE').iloc[-1]

In [19]:
last_raps_game

SEASON_ID                     22017
TEAM_ID                  1610612738
TEAM_ABBREVIATION               BOS
TEAM_NAME            Boston Celtics
GAME_ID                  0021701171
GAME_DATE                2018-04-04
MATCHUP                   BOS @ TOR
WL                                L
MIN                             237
PTS                              78
FGM                              25
FGA                              75
FG_PCT                        0.333
FG3M                              3
FG3A                             22
FG3_PCT                       0.136
FTM                              25
FTA                              28
FT_PCT                        0.893
OREB                              8
DREB                             35
REB                              43
AST                              10
STL                               7
BLK                               3
TOV                              16
PF                               16
PLUS_MINUS                    -18.0
Name: 552, dtype: object

In [20]:
game_id = last_raps_game.GAME_ID

In [30]:
game_id

'0021701171'

In [31]:
result = leaguegamefinder.LeagueGameFinder()

In [32]:
all_games = result.get_data_frames()[0]

In [33]:
full_game = all_games[all_games.GAME_ID == game_id]

In [27]:
full_game = all_games[all_games.GAME_ID == game_id]

In [34]:
full_game

Empty DataFrame
Columns: [SEASON_ID, TEAM_ID, TEAM_ABBREVIATION, TEAM_NAME, GAME_ID, GAME_DATE, MATCHUP, WL, MIN, PTS, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PLUS_MINUS]
Index: []

[0 rows x 28 columns]

In [36]:
from nba_api.stats.endpoints import playbyplayv2

In [37]:
pbp = playbyplayv2.PlayByPlayV2(game_id)

In [38]:
pbp = pbp.get_data_frames()[0]

In [39]:
pbp.head()

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
0,0021701171,2,12,0,1,8:11 PM,12:00,None,Start of 1st Period (8:11 PM EST),None,...,None,None,0,0,None,NaN,None,None,None,0
1,0021701171,4,10,0,1,8:11 PM,12:00,Jump Ball Valanciunas vs. Baynes: Tip to Anunoby,None,None,...,Celtics,BOS,4,1628384,OG Anunoby,1.610613e+09,Toronto,Raptors,TOR,1
2,0021701171,7,2,1,1,8:11 PM,11:38,MISS DeRozan 21' Jump Shot,None,None,...,None,None,0,0,None,NaN,None,None,None,1
3,0021701171,8,4,0,1,8:11 PM,11:36,None,None,Tatum REBOUND (Off:0 Def:1),...,None,None,0,0,None,NaN,None,None,None,1
4,0021701171,9,2,86,1,8:12 PM,11:21,None,None,MISS Horford 12' Turnaround Fadeaway Shot,...,None,None,0,0,None,NaN,None,None,None,1